services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: learnto
      MYSQL_USER: learnto
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - learnto

  web:
    image: learnto:latest
    container_name: learnto
    ports:
      - "8000:80"
    environment:
      APP_URL: http://localhost
      DB_HOST: db
    depends_on:
      - db

volumes:
  db_data:

networks:
  learnto:
    driver: bridge
